olx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    path('<slug:category_slug>', views.productlist, name='product_list_category'),
    path('detail/<slug:product_slug>', views.productdetail, name='product_detail'),


]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Product(models.Model):

    # categorical data
    CONDITION_TYPE = (
        ("New", "New"),
        ("Used", "Used"),
    )

    # contain all products informations
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE) # one to many
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=5000)
    condition = models.CharField(max_length=100, choices=(CONDITION_TYPE))
    price = models.DecimalField(max_digits=10, decimal_places=5)
    created = models.DateTimeField()
    image = models.ImageField(upload_to='main_products/', blank=True, null=True)

    slug = models.SlugField(blank=True, null=True )

    # for new product if slug field empty then product-name make slug
    def save(self,*args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.product.name


    # fix name on PRODUCT section categorys
    class Meta:
        verbose_name = 'product image'
        verbose_name_plural = 'product images'




class Category(models.Model):
    # for product category
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/', blank=True, null=True)

    slug = models.SlugField(blank=True, null=True )


    # for new category if slug field empty then auto pick
    def save(self,*args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)


    # fix name on PRODUCT section categorys
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name



class Brand(models.Model):
    # for product brand
    brand_name = models.CharField(max_length=50)
    
    # fix name on PRODUCT section categorys
    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand_name










        

product/views.py
from django.shortcuts import render
from .models import Product, ProductImages, Category

from django.core.paginator import Paginator
from django.db.models import Count # for count all data each category

# for search we use   Complex lookups with Q objects
from django.db.models import Q


from django.shortcuts import get_object_or_404 

# Create your views here.

def productlist(request, category_slug=None):
    category = None
    products = Product.objects.all()  # product_list
    categories = Category.objects.annotate(total_products=Count('product'))  #count data on each category_list

    # display items by clicking on category
    if category_slug:
        category = get_object_or_404(Category, slug= category_slug)
        products = products.filter(category=category)
    
    # filter for search
    search_query = request.GET.get('q')
    if search_query :
        products = products.filter(
            Q(name__icontains = search_query) |
            Q(brand__brand_name__icontains = search_query) |
            Q(condition__icontains = search_query) |
            Q(created__icontains = search_query)

        )



    # pagination
    paginator = Paginator(products, 3) # Show 25 contacts per page.
    page = request.GET.get('page') 
    products = paginator.get_page(page)


    context = {'products': products, 'categories':categories, 'category': category }
    template_name = 'product/product_list.html'
    return render(request,template_name, context)


def productdetail(request, product_slug):
    productdetail = Product.objects.get(slug=product_slug)  # pick specific products
    productimages = ProductImages.objects.filter(product=productdetail)



    context = {'product_detail' : productdetail, 'product_images' : productimages}
    template_name = 'product/product_detail.html'
    return render(request,template_name, context)

product/templates/product/product_detail.html

{% extends "base.html" %}

{% load static %}

{% block body %}

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">

			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<!-- <li><a href="index.html">Home</a></li> -->
				<li class="active"> <a href="{% url 'product:product_list' %}"> All Ads </a></li>

				{% if category %}
				
				<li class="active">{{category}}</li>

				{%endif%}

			</ol>

			<div class="product-desc">
				<div class="col-md-7 product-view">

					<h2>{{ product_detail.name }}</h2>
					<p> <h4>owner: <strong> {{ product_detail.owner }} </strong></h4> <a> category : {{ product_detail.category }}</a>| created: {{ product_detail.created }}</p>
					<div class="flexslider">
						<ul class="slides">
							
							{% for image in product_images %}

							<li data-thumb="{{image.image.url}}">
								<img src="{{image.image.url}}" />
							</li>
							
							{% endfor %}

						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a>{{ product_detail.brand }}</a></h4>
						<p><strong>Discription : {{ product_detail.description }} </strong> </p>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">$  {{ product_detail.price }} </h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4> {{ product_detail.condition }} </h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{ product_detail.category }} </h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>+8801734522557</p>
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">This project made my <strong>Monad_Wizard</strong></a></li>								
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Occupational Health and Safety.</a></li>
								<li><a href="#">Biological Safety.</a></li>
								<li><a href="#">Plant Safety.</a></li>
								<li><a href="#">Transportation and Storage Safety.</a></li>
								<li><a href="#">Incident and Emergency Planning.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->

{% endblock body %}

product/templates/product/product_list.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% extends "base.html" %}

{% block body %}

	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">

			<div class="all-categories">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">
					
					{% for category in categories %}

					<li><a href="{% url 'product:product_list_category' category.slug %}">{{category}} <span class="num-of-ads">{{category.total_products}}</span></a></li>

					{% endfor %}

				</ul>
			</div>
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<!-- <li><a href="index.html">Home</a></li> -->
				<li class="active"> <a href="{% url 'product:product_list' %}"> All Ads </a></li>

				{% if category %}
				
				<li class="active">{{category}}</li>

				{%endif%}

			</ol>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
						<h3 class="sear-head">Search</h3>
						
						<form method="GET" action="{% url 'product:product_list' %}">
							<input type="text" placeholder="Product name..." name='q' required="">
							<input type="submit" value=" ">
						</form>
					</div>


					<div class="featured-ads">
						<h2 class="sear-head fer">Featured Ads</h2>
						<div class="featured-ad">
							<a href="single.html">
								<div class="featured-ad-left">
									<img src="images/f1.jpg" title="ad image" alt="" />
								</div>
								<div class="featured-ad-right">
									<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
									<p>$ 450</p>
								</div>
								<div class="clearfix"></div>
							</a>
						</div>
						<div class="featured-ad">
							<a href="single.html">
								<div class="featured-ad-left">
									<img src="images/f2.jpg" title="ad image" alt="" />
								</div>
								<div class="featured-ad-right">
									<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
									<p>$ 380</p>
								</div>
								<div class="clearfix"></div>
							</a>
						</div>
						<div class="featured-ad">
							<a href="single.html">
								<div class="featured-ad-left">
									<img src="images/f3.jpg" title="ad image" alt="" />
								</div>
								<div class="featured-ad-right">
									<h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
									<p>$ 560</p>
								</div>
								<div class="clearfix"></div>
							</a>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">

							<div id="myTabContent" class="tab-content">
								<div role="tabpanel" class="tab-pane fade in active" id="home"
									aria-labelledby="home-tab">
									<div>
										<div id="container">


											<div class="clearfix"></div>
											<ul class="list">

												{% for product in products %}


												<a href="{% url 'product:product_detail' product.slug %}">
													<li>
														<img src="{{product.image.url}}" title="" alt="" />
														<section class="list-left">
															<h5 class="title"> {{ product.name }} </h5>
															<span class="adprice">{{ product.price }}</span>
															<p class="catpath">{{ product.brand }}</p>
														</section>
														<section class="list-right">
															<span class="date">{{ product.created }}</span>
															<span class="category">{{ product.category }}</span>
														</section>
														<div class="clearfix"></div>
													</li>
												</a>

												{% endfor %}

											</ul>
										</div>
									</div>
								</div>

<!-- pagination -->

{% if products.has_other_pages %}

<ul class="pagination pagination-sm">
	{% if products.has_previous %}
		<li><a href="?page={{ products.previous_page_number }}">Prev</a></li>
	{% else %}
		<li class="disabled"></li>

	{% endif %}

	{% for pages in products.paginator.page_range %}
		{% if products.number == pages %}
			<li><a href="#">{{pages}}</a></li>
		{% else %}
			<li><a href="?page={{pages}}">{{pages}}</a></li>								
		{% endif %}

	{% endfor %}

	{% if products.has_next %}
		<li><a href="?page={{ products.next_page_number }}">Next</a></li>
	{% else %}
		<li class="disabled"></li>								
	{% endif %}

</ul>		
{% endif %}


<!-- pagination  -->




							</div>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- // Products -->

{% endblock body %}

templates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>resale</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
	<!-- for-mobile-apps -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
	<script
		type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //for-mobile-apps -->
	<!--fonts-->
	<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
	<link
		href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
		rel='stylesheet' type='text/css'>
	<!--//fonts-->
	<!-- js -->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<!-- js -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-select.js' %}"></script>
	<script>
		$(document).ready(function () {
			var mySelect = $('#first-disabled2');

			$('#special').on('click', function () {
				mySelect.find('option:selected').prop('disabled', true);
				mySelect.selectpicker('refresh');
			});

			$('#special2').on('click', function () {
				mySelect.find('option:disabled').prop('disabled', false);
				mySelect.selectpicker('refresh');
			});

			$('#basic2').selectpicker({
				liveSearch: true,
				maxOptions: 1
			});
		});
	</script>
	<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
	<link href="{% static 'css/jquery.uls.css" rel="stylesheet' %}" />
	<link href="{% static 'css/jquery.uls.grid.css" rel="stylesheet' %}" />
	<link href="{% static 'css/jquery.uls.lcd.css" rel="stylesheet' %}" />
	<!-- Source -->
	<script src="{% static 'js/jquery.uls.data.js' %}"></script>
	<script src="{% static 'js/jquery.uls.data.utils.js' %}"></script>
	<script src="{% static 'js/jquery.uls.lcd.js' %}"></script>
	<script src="{% static 'js/jquery.uls.languagefilter.js' %}"></script>
	<script src="{% static 'js/jquery.uls.regionfilter.js' %}"></script>
	<script src="{% static 'js/jquery.uls.core.js' %}"></script>
	<script>
		$(document).ready(function () {
			$('.uls-trigger').uls({
				onSelect: function (language) {
					var languageName = $.uls.data.getAutonym(language);
					$('.uls-trigger').text(languageName);
				},
				quickList: ['en', 'hi', 'he', 'ml', 'ta', 'fr'] //FIXME
			});
		});
	</script>
</head>

<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="{% url 'product:product_list' %}"><span>Monad</span>Wizard</a>
			</div>
			<div class="header-right">
				<a class="account" href="login.html">My Account</a>

			</div>
		</div>
	</div>
	<div class="main-banner banner text-center">
		<div class="container">
			<h1>Sell or Advertise <span class="segment-heading"> anything online </span> with Resale</h1>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
			<a href="post-ad.html">Post Free Ad</a>
		</div>
	</div>
	<!-- content-starts-here -->

	{% block body %}

	

	{% endblock body %}
	<!--footer section start-->
	<footer>
		<div class="footer-top">
			<div class="container">
				<div class="foo-grids">
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Who We Are</h4>
						<p>It is a long established fact that a reader will be distracted by the readable content of a
							page when looking at its layout.</p>
						<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to
							using 'Content here.</p>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Help</h4>
						<ul>
							<li><a href="howitworks.html">How it Works</a></li>
							<li><a href="sitemap.html">Sitemap</a></li>
							<li><a href="faq.html">Faq</a></li>
							<li><a href="feedback.html">Feedback</a></li>
							<li><a href="contact.html">Contact</a></li>
							<li><a href="typography.html">Shortcodes</a></li>
						</ul>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Information</h4>
						<ul>
							<li><a href="regions.html">Locations Map</a></li>
							<li><a href="terms.html">Terms of Use</a></li>
							<li><a href="popular-search.html">Popular searches</a></li>
							<li><a href="privacy.html">Privacy Policy</a></li>
						</ul>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Contact Us</h4>
						<span class="hq">Our headquarters</span>
						<address>
							<ul class="location">
								<li><span class="glyphicon glyphicon-map-marker"></span></li>
								<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
								<div class="clearfix"></div>
							</ul>
							<ul class="location">
								<li><span class="glyphicon glyphicon-earphone"></span></li>
								<li>+0 561 111 235</li>
								<div class="clearfix"></div>
							</ul>
							<ul class="location">
								<li><span class="glyphicon glyphicon-envelope"></span></li>
								<li><a href="mailto:info@example.com">mail@example.com</a></li>
								<div class="clearfix"></div>
							</ul>
						</address>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by <a href="http://w3layouts.com/"> W3layouts</a>
					</p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</footer>
	<!--footer section end-->
</body>

</html>